/*
@TargetNode='localhost'
@GeneratedBy=levolkov
@GenerationDate=05/15/2025 17:49:31
@GenerationHost=DESKTOP-PD6E4GG
*/

instance of MSFT_nxPackageResource as $MSFT_nxPackageResource1ref
{
ModuleVersion = "1.0";
 SourceInfo = "::9::14::nxPackage";
 ModuleName = "nx";
 Ensure = "Present";
 ResourceID = "[nxPackage]httpd";
 Name = "httpd";
 PackageManager = "Yum";
 ConfigurationName = "LAMPServer";
};
instance of MSFT_nxPackageResource as $MSFT_nxPackageResource2ref
{
ModuleVersion = "1.0";
 SourceInfo = "::9::14::nxPackage";
 ModuleName = "nx";
 Ensure = "Present";
 ResourceID = "[nxPackage]mod_ssl";
 Name = "mod_ssl";
 PackageManager = "Yum";
 ConfigurationName = "LAMPServer";
};
instance of MSFT_nxPackageResource as $MSFT_nxPackageResource3ref
{
ModuleVersion = "1.0";
 SourceInfo = "::9::14::nxPackage";
 ModuleName = "nx";
 Ensure = "Present";
 ResourceID = "[nxPackage]php";
 Name = "php";
 PackageManager = "Yum";
 ConfigurationName = "LAMPServer";
};
instance of MSFT_nxPackageResource as $MSFT_nxPackageResource4ref
{
ModuleVersion = "1.0";
 SourceInfo = "::9::14::nxPackage";
 ModuleName = "nx";
 Ensure = "Present";
 ResourceID = "[nxPackage]php-mysqlnd";
 Name = "php-mysqlnd";
 PackageManager = "Yum";
 ConfigurationName = "LAMPServer";
};
instance of MSFT_nxPackageResource as $MSFT_nxPackageResource5ref
{
ModuleVersion = "1.0";
 SourceInfo = "::9::14::nxPackage";
 ModuleName = "nx";
 Ensure = "Present";
 ResourceID = "[nxPackage]mariadb";
 Name = "mariadb";
 PackageManager = "Yum";
 ConfigurationName = "LAMPServer";
};
instance of MSFT_nxPackageResource as $MSFT_nxPackageResource6ref
{
ModuleVersion = "1.0";
 SourceInfo = "::9::14::nxPackage";
 ModuleName = "nx";
 Ensure = "Present";
 ResourceID = "[nxPackage]mariadb-server";
 Name = "mariadb-server";
 PackageManager = "Yum";
 ConfigurationName = "LAMPServer";
};
instance of MSFT_nxServiceResource as $MSFT_nxServiceResource1ref
{
ModuleVersion = "1.0";
 Enabled = True;
 Controller = "systemd";
 SourceInfo = "::18::14::nxService";
 ModuleName = "nx";
 ResourceID = "[nxService]httpd";
 Name = "httpd";
 State = "Running";
 ConfigurationName = "LAMPServer";
};
instance of MSFT_nxServiceResource as $MSFT_nxServiceResource2ref
{
ModuleVersion = "1.0";
 Enabled = True;
 Controller = "systemd";
 SourceInfo = "::18::14::nxService";
 ModuleName = "nx";
 ResourceID = "[nxService]mariadb";
 Name = "mariadb";
 State = "Running";
 ConfigurationName = "LAMPServer";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="levolkov";

                        GenerationDate="05/15/2025 17:49:31";

                        GenerationHost="DESKTOP-PD6E4GG";

                        Name="LAMPServer";

                    };
