/*
@TargetNode='localhost'
@GeneratedBy=levolkov
@GenerationDate=05/17/2025 19:12:48
@GenerationHost=DESKTOP-PD6E4GG
*/

instance of DSC_TimeZone as $DSC_TimeZone1ref
{
IsSingleInstance = "Yes";
 ModuleVersion = "10.0.0";
 ModuleName = "ComputerManagementDsc";
 TimeZone = "Eastern Standard Time";
 SourceInfo = "::25::9::TimeZone";
 ResourceID = "[TimeZone]TimeZoneConfig";
 ConfigurationName = "TimeZoneCustom";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="levolkov";

                        GenerationDate="05/17/2025 19:12:48";

                        GenerationHost="DESKTOP-PD6E4GG";

                        Name="TimeZoneCustom";

                    };
