trigger:
  branches:
    include:
      - users/*
  paths:
    include:
      - /kits/jumpstart-vm/*
    exclude:
      - /**/*.md
      - /secret/*.*
      - /.attachments

variables:
  - template: Variables.yaml

pool: $(agent_pool)

#remove this if not planning to use image builder
resources:
  pipelines:
  - pipeline: image-source
    source: jumpstart-image-builder-sig       #<--- Verify source matches name of image builder pipeline
    trigger:
      branches:
        include:
        - master

stages:
  - template: ./Layers.yaml
    parameters:
      environment: dev

      getImageLayers: virtualmachine
      projectName: ${{ variables.projectName }}
      pipelineId: ${{ variables.pipelineId }}
      runId: $(resources.pipeline.image-source.runID)
      preferTriggeringPipeline: ${{ variables.preferTriggeringPipeline }}
      downloadPath: ${{ variables.downloadPath }}

      # When setting "skip:  true", ensure the first layer to run has "start: start"
      layers:
        - name: resourcegroup
          type: resourcegroup
          version: "0.0.1"
          skip: false
          dependencies:
            start: start

        - name: networking
          type: networking
          version: "0.0.1"
          skip: false
          dependencies:
            resourcegroup: resourcegroup

        - name: loganalytics
          type: loganalytics
          version: "0.0.1"
          skip: false
          dependencies:
            resourcegroup: resourcegroup

        - name: recoveryservicesvault
          type: recoveryservicesvault
          version: "0.0.1"
          skip: false
          dependencies:
            resourcegroup: resourcegroup

        - name: azuremonitor
          type: azuremonitor
          version: "0.0.1"
          skip: false
          dependencies:
            resourcegroup: resourcegroup

        - name: vm_alerts
          type: vm_alerts
          version: "0.0.1"
          skip: false
          dependencies:
            resourcegroup: resourcegroup
            loganalytics: loganalytics
            azuremonitor: azuremonitor

        - name: vm_dashboards
          type: vm_dashboards
          version: "0.0.1"
          skip: false
          dependencies:
            resourcegroup: resourcegroup
            loganalytics: loganalytics

        - name: vm_workbooks
          type: vm_workbooks
          version: "0.0.1"
          skip: false
          dependencies:
            resourcegroup: resourcegroup
            loganalytics: loganalytics

        - name: keyvault
          type: keyvault
          version: "0.0.1"
          skip: false
          dependencies:
            networking: networking
            loganalytics: loganalytics

        - name: storage
          type: storage
          version: "0.0.1"
          skip: false
          dependencies:
            keyvault: keyvault
            networking: networking

        - name: keyvaultdiagnosticlogs
          type: keyvaultdiagnosticlogs
          version: "0.0.1"
          skip: false
          dependencies:
            keyvault: keyvault
            storage: storage
        
        - name: nsgflowlogs
          type: nsgflowlogs
          version: "0.0.1"
          skip: false
          dependencies:
            networking: networking
            storage: storage

        - name: azsql
          type: azsql
          version: "0.0.1"
          skip: false
          dependencies:
            resourcegroup: resourcegroup
            keyvault: keyvault

        - name: loadbalancer
          type: loadbalancer
          version: "0.0.1"
          skip: false
          dependencies:
            networking: networking

        - name: privatelinkservice
          type: privatelinkservice
          version: "0.0.1"
          skip: false
          dependencies:
            loadbalancer: loadbalancer

        - name: applicationgateway
          type: applicationgateway
          version: "0.0.1"
          skip: false
          dependencies:
            storage: storage
            loganalytics: loganalytics

        - name: virtualmachine
          type: virtualmachine
          version: "0.0.1"
          skip: false
          dependencies:
            loadbalancer: loadbalancer
            storage: storage
            privateendpoints: privateendpoints
            applicationgateway: applicationgateway
            recoveryservicesvault: recoveryservicesvault

        - name: privateendpoints
          type: privateendpoints
          version: "0.0.1"
          skip: false
          dependencies:
            keyvault: keyvault
            storage: storage
            azsql: azsql

        - name: privatednszone
          type: privatednszone
          version: "0.0.1"
          skip: false
          dependencies:
            privateendpoints: privateendpoints

        - name: privatednsarecord
          type: privatednsarecord
          version: "0.0.1"
          skip: false
          dependencies:
            privatednszone: privatednszone